createcampaign/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', createCampaign, name='createCampaign'),
]

donationlist/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', donationlist, name='doantionlist'),
]

homepage/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Home, name='Home'),
]

login/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = 'login'

urlpatterns = [
    path('logout/', logout, name="logout"),
]

news/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('news', news, name='news'),]

sinarperakv2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls', 'homepage'), namespace='homepage')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('donationlist/', include(('donationlist.urls', 'donationlist'), namespace='donationlist')),
	path('createcampaign/', include(('createcampaign.urls', 'createcampaign'), namespace='createcampaign')),
    path('login/', include(('login.urls', 'login'), namespace='login')),
    # path('logout/', views.logout, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
]

testimoni/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('testimoni', views.index, name='index'),
        path('tambah', views.add_testimoni, name= 'tambah'),
]

browsecampaign/models.py
from django.db import models

# Create your models here.

createcampaign/models.py
from django.db import models

# Create your models here.

class Campaign(models.Model):
	Project_name = models.TextField(max_length = 40)
	Goal = models.TextField(max_length = 40)
	Donation_end_date= models.DateField(max_length = 50)
	Description = models.TextField(max_length = 250)
	image=models.FileField(upload_to = 'static/', default = 'static/None/no-img.jpg')

donationlist/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

testimoni/models.py
from django.db import models
class Testimoni(models.Model):
	testimony = models.TextField(max_length = 300)
# Create your models here.

createcampaign/forms.py
from django import forms

from .models import Campaign

class PostCampaign(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ('Project_name', 'Goal', 'Donation_end_date', 'Description','image')

browsecampaign/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from createcampaign.models import
# Create your views here.
response = {}
def campaignPage(request):
	return render(request, 'campaignPage.html')

def browseCampaign(request):
	campaigns = Campaign.objects.all()
	response['campaigns'] = campaigns
	html = 'browseCampaign.html'
	return render(request, html, response)

createcampaign/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Campaign
from .forms import PostCampaign
# Create your views here.
response = {}

def createCampaign(request):
	campaigns = Campaign.objects.all()
	response['campaigns'] = campaigns

	html = 'Create-Campaign.html'
	return render(request, html, response)
	
def savecampaign(request):
	form = PostCampaign(request.POST or None)
	if(request.method == 'POST'):
		response['Project_name'] = request.POST['Project_name']
		response['Goal'] = request.POST['Goal']
		response['Donation_end_date'] = request.POST['Donation_end_date']
		response['Description'] = request.POST['Description']
		response['image']=request.POST['image']
		myCampaign = Campaign(Project_name=response['Project_name'], Goal=response['Goal'], Donation_end_date=response['Donation_end_date'], Description=response['Description'],image=response['image'])
		myCampaign.save()
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

donationlist/views.py
from django.shortcuts import render

# Create your views here.
def donationlist(request):
    return render(request, 'donationlist.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    return render(request, 'home.html')

login/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
import requests
import json

def logout(request):
    request.session.flush()
    return HttpResponseRedirect('/')

news/views.py
from django.shortcuts import render

# Create your views here.
def news(request):
    return render(request, 'news.html')

testimoni/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect 
from .models import Testimoni 
from datetime import datetime 
import pytz 
import json
# Create your views here.
data_dict = {}
def index(request):
	data_dict = Testimoni.objects.all().values()
	return render(request,'testimoni.html',{'data_dict': }

def add_testimoni(request):
	if request.method == 'POST':
		act = request.POST['testimony']
		Testimoni.objects.create(testimony = act)
		return redirect('/testimoni/')
	
def convert_to_json(queryset):
	val = []
	for data in queryset:
		val.append(data)
	return val
		

browsecampaign/templates/browseCampaign.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SinarPerak</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
    <link href="navbar.html" rel="import">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}  
<div class="container"> 
    {% for data in campaigns %}
    <div class="row">
        <div class="col-sm">
            <p>{{ data.Project_name }}</p>
        </div>
        <div class="col-sm">
            <p>{{ data.Description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{%include 'footer.html'%}
</body>
</html>

browsecampaign/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url '#">Donate</a></p>
      <p class="ab"><a href="{% url '#">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'login:login' %}">Log in!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

browsecampaign/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:Home' %}">Home</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="#">Browse Campaign</a></li>
      <li><a href="#">Create Campaign!</a></li>

      {% if user.is_authenticated %}
    <li><p>Welcome, {{ name }}. Thanks for logging in.</p></li>
    <ul class="nav navbar-nav navbar-right">
      <li>
    {% csrf_token %}
        <a id="logout"class="g-signout2" href="{% url 'logout' %}" onclick="signOut()">LOGOUT</a></div>
    </li></ul>
{% else %}
   <li> <p>Welcome, new user. Please log in.</p></li>
   <ul class="nav navbar-nav navbar-right">
      <li>
    {% csrf_token %}
        <div class="g-signin2" data-onsuccess="onSignIn"></div>
    </li></ul>
{% endif %}
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

createcampaign/templates/Create-Campaign.html
{%load static%}
<!DOCTYPE html>
<!-- Homepage (hello.html), footer ,and header by Jeremy -->
<html>
<body>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  SinarPerak
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
  <link href="navbar.html" rel="import">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color: #80475E;color: white">
{%block content%}{%include 'navbar.html'%}{%endblock%}
<section style="margin-left: 30px;margin-top: 75px">
<form action="{% url 'hamri:savecampaign' %}" method="POST">
  {% csrf_token %}
  Project_name:<br>
  <input type="text" name="Project_name" value="Project_name" style="color:#80475E ">
  <br><br>
  Goal:<br>
  <input type="text" name="Goal" value="Goal">
  <br><br>
  Donation end date:<br>
  <input type="date" name="Donation_end_date" value="Donation_end_date" style="color:#80475E ">
  <br><br>
  Description:<br>
  <textarea name="message" rows="10" cols="30" style="color:#80475E ">Help each other by donating or join the campaign!</textarea>
  <br><br>
  <input type="file" name="image" accept="image/*">
  <br>
  <input type="submit" value="Submit" style="color:#80475E ">
</form>
</section>
<br>
<br>
<br>


{%include 'footer.html'%}
</body>
</html>

createcampaign/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url '#">Donate</a></p>
      <p class="ab"><a href="{% url '#">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'login:login' %}">Log in!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

createcampaign/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:Home' %}">Home</a></li>
      <li><a href="{% url 'news:news' %}">News</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="#">Browse Campaign</a></li>
      <li><a href="#">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'login:login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

donationlist/templates/donationlist.html
{%load static%}
<!-- Home page (hello.html), footer ,and header by Jeremy -->
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  SinarPerak
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'tp1css.css' %}" type="text/css">
  <link href="navbar.html" rel="import">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{%block content%}{%include 'navbar.html'%}{%endblock%}
<div class="container-fluid">
  <h2>Your Donation</h2>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SGI-2016-South_Georgia_%28Fortuna_Bay%29%E2%80%93King_penguin_%28Aptenodytes_patagonicus%29_04.jpg/220px-SGI-2016-South_Georgia_%28Fortuna_Bay%29%E2%80%93King_penguin_%28Aptenodytes_patagonicus%29_04.jpg" alt="Penguin" class="img-thumbnail">
      </div>
      <div class="col-sm">
        <h3>Besar Donasi</h3><br>
        <h3>Rp10.000.000,00</h3>
      </div>
    </div>
  </div>
</div>
{%include 'footer.html'%}
</body>
</html>

donationlist/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url '#">Donate</a></p>
      <p class="ab"><a href="{% url '#">Create Campaign!</a></p>
      <p class="ab"><a href="{% url 'login:login' %}">Log in!</a></p>
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

donationlist/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak">
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'homepage:Home' %}">Home</a></li>
      <li><a href="{% url 'news:news' %}">News</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="#">Browse Campaign</a></li>
      <li><a href="#">Create Campaign!</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'login:login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
    </ul>
  </div>
</nav>
<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

homepage/templates/footer.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->

{% block content %}
<body>
  <footer id="aboutus">

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <h1 ><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak"><br></h1>
      <p>
       SinarPerak is a non-profit foundation that mainly focused in disaster fund relief. We want you to be a part of our journey by helping us donating to one who needs.</p>
    </div>
     <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Act Now!<br></h1>
      <p class="ab"><a href="{% url '#">Donate</a></p>
      <p class="ab"><a href="{% url '#">Create Campaign!</a></p>
     
    </div>
    <div class="col-sm-4">
      <h1 style="font-size: 25px;color: #80475E;font-weight: bold">Contact Us<br></h1>
      <p><span class="glyphicon glyphicon-map-marker"></span> Jl. H. Amat No.3, Kukusan, Beji, Kota Depok, Jawa Barat 16425</p>
      <p><span class="glyphicon glyphicon-phone"></span> +62 85945319721</p>
      <p><span class="glyphicon glyphicon-envelope"></span> bantusesama@gmail.com</p> 
    </div>
      </div> 
    </div>
</footer>
  {% endblock %}

homepage/templates/navbar.html
{%load static%}

<!-- Home page (home.html), footer ,and header by Jeremy -->
{% block content %}
<nav class="navbar navbar-default navbar-fixed-top sticky-top"">
  <div class="container-fluid">
    <div class="navbar-header"><img src="{% static 'css/sinarperaklogo.png' %}" alt="SinarPerak">
    </div>

          <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
      <li><a href="{% url 'homepage:Home' %}">Home</a></li>
      <li><a href="#news ">News</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="#">Browse Campaign</a></li>
      <li><a href="#">Create Campaign!</a></li>
   
    <li>
            <a style="color:lightblue;">Hello {{ user.username }}</a>
          </li>
        </ul>
    <ul class="nav navbar-nav navbar-right">
       
      <li >
           <a  href="{% url 'login:logout' %}"><span class="glyphicon glyphicon-user"></span>LOGOUT</a>
          </li>
        </ul>
          {% else %}
          <li><a href="{% url 'homepage:Home' %}">Home</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#aboutus">About us</a></li>
      <li><a href="#">Browse Campaign</a></li>
      <li><a href="#">Create Campaign </a></li>
      <li>
            <a style="color:lightblue;">Hello please login!</a>
          </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
       <li>
      <a href="{% url 'social:begin' 'google-oauth2' %}"><span class="glyphicon glyphicon-user"></span>LOGIN</a>
          </li>
        </ul>
          {% endif %}
</div>
    </nav>

<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if 
  });
})
</script>
{% endblock %}

login/templates/login.html
{%load static%}
<!DOCTYPE html>
<!-- Homepage (hello.html), footer ,and header by Jeremy -->
<html>
<body>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  SinarPerak
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="google-signin-client_id" content='816164880634-adbiufa05kppnv6lkva0dusa2p54rl86.apps.googleusercontent.com'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/tp1css.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
          <script src="{% static 'js/helo.js' %}" type="text/javascript"></script>
</head>
<body class="body-login d-flex flex-column justify-content-center align-items-center">
	{%include 'navbar.html'%}
<h1></h1>
<section class="d-flex justify-content-center align-items-center">
    {% csrf_token %}
    <div class="login container d-flex flex-column justify-content-center align-items-center">
        <h5 align="center">Please Login First with Your Google Account!</h5>
        <div class="g-signin2" data-onsuccess="onSignIn"></div>
    </div>
</section>
{%include 'footer.html'%}
</body>
</html>

news/templates/news.html
{%load static%}
<!DOCTYPE html>
<!-- Homepage (hello.html), footer ,and header by Jeremy -->
<html>
<body>
<head>
<!DOCTYPE html>
<html lang="en">
<head>
<title>
  SinarPerak
</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/tp1css.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  {%block content%}{%include 'navbar.html'%}{%endblock%}
this is news platform hehehe still progressing tho
{%include 'footer.html'%}
</body>
</html>